import numpy as np

def sum_as_string(a: int, b: int) -> str: ...

def mult(a: float, x: np.ndarray) -> np.ndarray: ...

def axpy(a: float, x: np.ndarray, y: np.ndarray) -> np.ndarray: ...

def create_rgb_from_arr(x: np.ndarray) -> np.ndarray: ...

def apply_color_map(x: np.ndarray) -> np.ndarray: ...

def apply_color_map_with_take(x: np.ndarray) -> np.ndarray: ...
